# .github/workflows/ci-cd.yml
name: Python CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          pytest tests/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    # 這裡可以根據您的部署需求添加實際的部署步驟
    steps:
    - name: Deploy to production
      run: |
        echo "Deploying to production server"
        # 在這裡添加您的部署腳本，例如 SSH 到伺服器、拉取代碼等